export const LOCATION_CATEGORIES = [
  "Restaurant",
  "Hospital",
  "Gas Station",
  "Drive",
  "Park",
  "School",
  "Shopping Mall",
  "Bank",
  "Gym",
  "Pharmacy",
  "Library",
  "Post Office",
  "Hotel",
  "Coffee Shop",
  "Bar",
  "Movie Theater",
  "Museum",
  "Airport",
  "Train Station",
  "Bus Stop",
  "Police Station",
  "Fire Station",
  "Church",
  "Mosque",
  "Temple",
  "Supermarket",
  "Convenience Store",
  "Beach",
  "Zoo",
  "Stadium"
];
